version: '3'
services:
  app:
    container_name: whiskers
    restart: always 
    build: . 
    ports: 
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
    - "27017:27017"
